SharingCars/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',

    url(r'^', include('sharingcarapp.urls')),
)

sharingcarapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from sharingcarapp.views.Users.ApplyRouteUserView import ApplyRouteUserView
from sharingcarapp.views.Users.RouteUserView import RouteUserView
from sharingcarapp.views.Users.StopRouteUserView import StopRouteUserView
from sharingcarapp.views.Users.UserUserView import UserUserView
from sharingcarapp.views.Users.AnnouncementUserView import AnnouncementUserView
from sharingcarapp.views.Users.StopAnnouncementUserView import StopAnnouncementUserView
from sharingcarapp.views.all.IndexAllView import IndexAllView
from sharingcarapp.views.all.RouteAllView import RouteAllView

urlpatterns = patterns('',
    url(r'^$', IndexAllView.index, name='index'),
    url(r'^login/?$', 'django.contrib.auth.views.login',{'template_name': 'login.html'}),
    url(r'^logout/?$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^route/user/create$', RouteUserView.create, name='create_route'),
    url(r'^route/user/addStop', StopRouteUserView.create, name='create_stop_route'),
    url(r'^route/user/saveStop$', StopRouteUserView.saveStop, name='save_stop_route'),
    url(r'^route/user/saveMoreStop$', StopRouteUserView.saveMoreStop, name='save_more_stop_route'),
    url(r'^route/user/save$', RouteUserView.save, name='save_route'),
    url(r'^user/register$', UserUserView.create, name='user_register'),
    url(r'^user/save$', UserUserView.save, name='user_save'),
    url(r'^route/all$', RouteAllView.all, name='all_routes'),
    url(r'^route/show', RouteAllView.show, name='show_routes'),
    url(r'^route/user/apply', ApplyRouteUserView.create, name='create_apply_route'),
    url(r'^route/user/saveApply$', ApplyRouteUserView.save, name='save_apply_route'),
    url(r'^route/user/recommendations', UserUserView.recommendations, name='recommendations'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^announcement/user/create$', AnnouncementUserView.create, name='create_announcement'),
    url(r'^announcement/user/save$', AnnouncementUserView.save, name='save_announcement'),
    url(r'^announcement/user/addStop$', StopAnnouncementUserView.create, name='save_more_stop_announcement'),
    url(r'^announcement/user/saveStop$', StopAnnouncementUserView.saveStop, name='save_stop_announcement'),
    url(r'^announcement/user/saveMoreStop$', StopAnnouncementUserView.saveMoreStop, name='save_more_stop_announcement'),
)

sharingcarapp/models/Administrator.py
from sharingcarapp.models.Actor import Actor


class Administrator(Actor):
    pass

sharingcarapp/models/Day.py
from django.db import models
from sharingcarapp.models.Route import Route

__author__ = 'Ruben'

class Day(models.Model):
    day = models.IntegerField()
    departTime = models.CharField(max_length=64)
    returnTime = models.CharField(max_length=64)
    active = models.BooleanField()

    route = models.ForeignKey(Route)

sharingcarapp/forms/ApplyRouteCreateForm.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.validators import MinValueValidator

__author__ = 'Ruben'

class ApplyRouteCreateForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(attrs={'class' : 'form-control', 'placeholder' : 'Escriba lo que quiera comunicarle al dueño del anuncio.'}), label="Comentario", required=True)

sharingcarapp/forms/CreateAnnouncementForm.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.validators import MinValueValidator
import datetime

__author__ = 'Ruben'
ROUTE_KIND = (('','Elija una opción'),('1','Oferta'),('2','Demanda'))

class CreateAnnouncementForm(forms.Form):
    origin = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Origen'}),max_length=64, label="Origen", required=True)
    destination = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Destino'}),max_length=64, label="Destino", required=True)
    kind = forms.ChoiceField(widget=forms.Select(attrs={'class' : 'form-control'}), label='Tipo de anuncio', required=True, choices=ROUTE_KIND)
    seating = forms.IntegerField(widget=forms.NumberInput(attrs={'class' : 'form-control', 'placeholder' : 'Numero de plazas', 'min': '0'}),validators=[MinValueValidator(0)], label="Plazas")
    unitPrice = forms.DecimalField(widget=forms.NumberInput(attrs={'class' : 'form-control', 'placeholder' : 'Precio por persona', 'min': '0'}),max_digits=5, decimal_places=2, validators=[MinValueValidator(0)], label='Precio')
    description = forms.CharField(widget=forms.Textarea(attrs={'class' : 'form-control', 'placeholder' : 'Descripción'}),label="Descripción", required=True)
    date = forms.DateField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Hora de salida'}), initial=datetime.date.today(), label="Fecha")
    departTime = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Hora de salida'}),max_length=32, label="Hora de salida", required=False)

sharingcarapp/forms/CreateRouteForm.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.validators import MinValueValidator

__author__ = 'Ruben'
ROUTE_KIND = (('', 'Elija una opción'), ('1', 'Oferta'), ('2', 'Demanda'))


class CreateRouteForm(forms.Form):
    origin = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Origen'}), max_length=64, label="Origen", required=True)
    destination = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Destino'}), max_length=64, label="Destino", required=True)
    kind = forms.ChoiceField(widget=forms.Select(attrs={'class' : 'form-control'}), label='Tipo de ruta', required=True, choices=ROUTE_KIND)
    seating = forms.IntegerField(widget=forms.NumberInput(attrs={'class' : 'form-control', 'placeholder' : 'Numero de plazas', 'min': '0'}),validators=[MinValueValidator(0)], label="Plazas")
    unitPrice = forms.DecimalField(widget=forms.NumberInput(attrs={'class' : 'form-control', 'placeholder' : 'Precio por persona', 'min': '0'}),max_digits=5, decimal_places=2, validators=[MinValueValidator(0)], label='Precio')
    description = forms.CharField(widget=forms.Textarea(attrs={'class' : 'form-control', 'placeholder' : 'Descripción'}),label="Descripción", required=True)

    # Monday
    monday_departTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de salida'}),max_length=32, label="Hora de salida", required=False)
    monday_returnTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de vuelta'}),max_length=32, label="Hora de vuelta", required=False)
    # Tuesday
    tuesday_departTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de salida'}),max_length=32, label="Hora de salida", required=False)
    tuesday_returnTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de vuelta'}),max_length=32, label="Hora de vuelta", required=False)
    # Wednesday
    wednesday_departTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de salida'}),max_length=32, label="Hora de salida", required=False)
    wednesday_returnTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de vuelta'}),max_length=32, label="Hora de vuelta", required=False)
    # Thursday
    thursday_departTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de salida'}),max_length=32, label="Hora de salida", required=False)
    thursday_returnTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de vuelta'}),max_length=32, label="Hora de vuelta", required=False)
    # Friday
    friday_departTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de salida'}),max_length=32, label="Hora de salida", required=False)
    friday_returnTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de vuelta'}),max_length=32, label="Hora de vuelta", required=False)
    # Saturday
    saturday_departTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de salida'}),max_length=32, label="Hora de salida", required=False)
    saturday_returnTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de vuelta'}),max_length=32, label="Hora de vuelta", required=False)
    # Sunday
    sunday_departTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de salida'}),max_length=32, label="Hora de salida", required=False)
    sunday_returnTime = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Hora de vuelta'}),max_length=32, label="Hora de vuelta", required=False)

    def clean(self):
        monday_departTime = self.cleaned_data['monday_departTime']
        monday_returnTime = self.cleaned_data['monday_returnTime']

        tuesday_departTime = self.cleaned_data['tuesday_departTime']
        tuesday_returnTime = self.cleaned_data['tuesday_returnTime']

        wednesday_departTime = self.cleaned_data['wednesday_departTime']
        wednesday_returnTime = self.cleaned_data['wednesday_returnTime']

        thursday_departTime = self.cleaned_data['thursday_departTime']
        thursday_returnTime = self.cleaned_data['thursday_returnTime']

        friday_departTime = self.cleaned_data['friday_departTime']
        friday_returnTime = self.cleaned_data['friday_returnTime']

        saturday_departTime = self.cleaned_data['saturday_departTime']
        saturday_returnTime = self.cleaned_data['saturday_returnTime']

        sunday_departTime = self.cleaned_data['sunday_departTime']
        sunday_returnTime = self.cleaned_data['sunday_returnTime']

        # Validations for departTime and returnTime of Monday
        if (monday_returnTime == "" and monday_departTime !="") or (monday_returnTime != "" and monday_departTime ==""):
            self.add_error('monday_departTime', "La hora de salida y de vuelta para el lunes no están bien configuradas, por favor, corríjalo y vuelva a enviar")
        else:
            if validate_hour(monday_departTime):
                self.add_error('monday_departTime', "La hora de salida para el lunes no tiene la estructura correcta (Por ejemplo: 15:30)")
            elif  validate_hour(monday_returnTime):
                self.add_error('monday_departTime', "La hora de vuelta para el lunes no tiene la estructura correcta (Por ejemplo: 15:30)")
            elif validate_depart_return(monday_departTime, monday_returnTime):
                self.add_error('monday_departTime', "La hora de vuelta para el lunes debe de ser posterior a la hora de salida")

        # Validations for departTime and returnTime of Tuesday
        if (tuesday_returnTime == "" and tuesday_departTime !="") or (tuesday_returnTime != "" and tuesday_departTime ==""):
            self.add_error('monday_departTime', "La hora de salida y de vuelta para el martes no están bien configuradas, por favor, corríjalo y vuelva a enviar")
        else:
            if validate_hour(tuesday_departTime):
                self.add_error('monday_departTime', "La hora de salida para el martes no tiene la estructura correcta (Por ejemplo: 15:30)")
            elif  validate_hour(tuesday_returnTime):
                self.add_error('monday_departTime', "La hora de vuelta para el martes no tiene la estructura correcta (Por ejemplo: 15:30)")
            elif validate_depart_return(tuesday_departTime, tuesday_returnTime):
                self.add_error('monday_departTime', "La hora de vuelta para el martes debe de ser posterior a la hora de salida")

        # Validations for departTime and returnTime of Wednesday
        if (wednesday_returnTime == "" and wednesday_departTime !="") or (wednesday_returnTime != "" and wednesday_departTime ==""):
            self.add_error('monday_departTime', "La hora de salida y de vuelta para el miércoles no están bien configuradas, por favor, corríjalo y vuelva a enviar")
        else:
            if validate_hour(wednesday_departTime):
                self.add_error('monday_departTime', "La hora de salida para el miércoles no tiene la estructura correcta (Por ejemplo: 15:30)")
            elif  validate_hour(wednesday_returnTime):
                self.add_error('monday_departTime', "La hora de vuelta para el miércoles no tiene la estructura correcta (Por ejemplo: 15:30)")
            elif validate_depart_return(wednesday_departTime, wednesday_returnTime):
                self.add_error('monday_departTime', "La hora de vuelta para el miércoles debe de ser posterior a la hora de salida")

        # Validations for departTime and returnTime of Thursday
        if (thursday_returnTime == "" and thursday_departTime !="") or (thursday_returnTime != "" and thursday_departTime ==""):
            self.add_error('monday_departTime', "La hora de salida y de vuelta para el jueves no están bien configuradas, por favor, corríjalo y vuelva a enviar")
        else:
            if validate_hour(thursday_departTime):
                self.add_error('monday_departTime', "La hora de salida para el jueves no tiene la estructura correcta (Por ejemplo: 15:30)")
            elif  validate_hour(thursday_returnTime):
                self.add_error('monday_departTime', "La hora de vuelta para el jueves no tiene la estructura correcta (Por ejemplo: 15:30)")
            elif validate_depart_return(thursday_departTime, thursday_returnTime):
                self.add_error('monday_departTime', "La hora de vuelta para el jueves debe de ser posterior a la hora de salida")

        # Validations for departTime and returnTime of Friday
        if (friday_returnTime == "" and friday_departTime !="") or (friday_returnTime != "" and friday_departTime ==""):
            self.add_error('monday_departTime', "La hora de salida y de vuelta para el viernes no están bien configuradas, por favor, corríjalo y vuelva a enviar")
        else:
            if validate_hour(friday_departTime):
                self.add_error('monday_departTime', "La hora de salida para el viernes no tiene la estructura correcta (Por ejemplo: 15:30)")
            elif  validate_hour(friday_returnTime):
                self.add_error('monday_departTime', "La hora de vuelta para el viernes no tiene la estructura correcta (Por ejemplo: 15:30)")
            elif validate_depart_return(friday_departTime, friday_returnTime):
                self.add_error('monday_departTime', "La hora de vuelta para el viernes debe de ser posterior a la hora de salida")

        # Validations for departTime and returnTime of Saturday

sharingcarapp/forms/StopForm.py
from django import forms

__author__ = 'Ruben'

class StopForm(forms.Form):
    stop = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Parada'}),max_length=64, label='Parada')

sharingcarapp/forms/UserRegisterForm.py
# -*- coding: utf-8 -*-
from datetime import date
from django import forms
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

__author__ = 'Ruben'
phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',message="El número de teléfono de estar en este formato: '+999999999'. Hasta 15 carácteres permitidos.")
class UserRegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Nombre de usuario'}),max_length=32, label="Nombre de usuario")
    password = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Contraseña', 'type':'password'}),max_length=32, label="Contraseña")
    confirm_password = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Confirmar contraseña', 'type':'password'}),max_length=32, label="Confirmar contraseña")
    name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Nombre'}),max_length=64, label="Nombre")
    surnames = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Apellidos'}),max_length=128, label="Apellidos")
    city = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Ciudad'}),max_length=128, label="Ciudad")
    birthdate = forms.DateField(label='Fecha de nacimiento', widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : date.today()}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : '+034 999999999'}),validators=[phone_regex], label='Número de teléfono', max_length=64)
    photo = forms.ImageField(widget=forms.FileInput(attrs={'type' : 'file'}),label= 'Imagen', required=False)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class' : 'form-control', 'placeholder' : 'Email'}),label= 'Email', required=True)

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            self.add_error('password', "Las contraseñas no coinciden.")
            self.add_error('confirm_password', "Las contraseñas no coinciden.")

        if User.objects.filter(username = self.cleaned_data['username']).exists():
            self.add_error('username', "Ya existe ese nombre de usuario")

        if User.objects.filter(email = self.cleaned_data['email']).exists():
            self.add_error('email', "Ya existe un usuario con ese email")

sharingcarapp/templates/route/list.html
{% extends 'master-page/master-page.html' %}
{% block title %} SharingCars {% endblock %}
{% block jumbotron %}{% load staticfiles  %}
    <div class="jumbotron">
        <div class="col-lg-12">
        {% for route in routes %}
            <div class="col-lg-12">
                <div class="col-lg-3">
                    <div class="col-lg-12">
                        {% if route.user.photo == 'default' %}
                            <img class="img-circle img-responsive center-block"  src="{% static 'user/image/default.jpg' %}" style="width:auto;height:200px" alt="">
                        {% else %}
                            <img class="img-circle img-responsive center-block"  src="{% static route.user.photo %}" style="width:auto;height:200px" alt="">
                        {% endif %}
                    </div>
                    <div class="col-lg-12">
                        {{ route.user.name }}
                    </div>
                    <div class="col-lg-12">
                        {{ route.user.surnames|truncatechars:50 }}
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="col-lg-12">
                        <div class="col-lg-6">
                            <b>Tipo de anuncio: </b> {% if route.kind == 1 %}Oferta{% else %}Demanda{% endif %}
                        </div>
                        <div class="col-lg-6">
                            <b>{{ route.unitPrice }}<span class="glyphicon glyphicon-euro" aria-hidden="true"></span> por persona  </b>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="col-lg-6">
                            <b>Origen: </b>{{ route.origin }}
                        </div>
                        <div class="col-lg-6">
                            <b>Destino: </b>{{ route.destination }}
                        </div>
                    </div>
                </div>
            </div>
              <div class="col-lg-12"><br></div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

sharingcarapp/templates/route/list2.html
{% extends 'master-page/master-page.html' %}
{% block title %} SharingCars {% endblock %}
{% block jumbotron %}{% load staticfiles %}

    <div class="jumbotron">
          {% for route in routes %}
              <div class="row col-lg-12">
                <div class="col-lg-3">
                    <div class="col-lg-12">
                        {% if route.user.photo == 'default' %}
                            <img class="img-circle img-responsive center-block"  src="{% static 'user/image/default.jpg' %}" style="width:auto;height:200px" alt="">
                        {% else %}
                            <img class="img-circle img-responsive center-block"  src="{% static route.user.photo %}" style="width:auto;height:200px" alt="">
                        {% endif %}
                    </div>
                    <div class="col-lg-12 text-center">
                        <a href="/user/profile?userId={{ route.user.id }}">{{ route.user.name }}</a>
                    </div>
                    <div class="col-lg-12 text-center">
                        <a href="/user/profile?userId={{ route.user.id }}">{{ route.user.surnames|truncatechars:50 }}</a>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="col-lg-12">
                        <div class="col-lg-6">
                            <b>Tipo de anuncio: </b> {% if route.kind == "1" %}Oferta{% else %}Demanda{% endif %}
                        </div>
                        <div class="col-lg-6">
                            <b>{{ route.unitPrice }}<span class="glyphicon glyphicon-euro" aria-hidden="true"></span> por persona  </b>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="col-lg-6">
                            <b>Origen: </b>{{ route.origin }}
                        </div>
                        <div class="col-lg-6">
                            <b>Destino: </b>{{ route.destination }}
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="col-lg-12">
                            <b>Fecha de creaci&oacute;n: </b>{{ route.creationMoment }}
                        </div>
                        <div class="col-lg-12">
                            <b>Plazas: </b>{{ route.seating }}
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="col-lg-12">
                            <b>Descripci&oacute;n: </b>{{ route.description }}
                        </div>
                    </div>
                      <div class="col-lg-12">
                        <div class="col-lg-12 text-center">
                            <h2>Horario</h2>
                        </div>
                        <div class="col-lg-12">
                            {% for day in route.day_set.all %}
                                {% if forloop.counter <= 4 %}
                                    <div class="col-lg-3 text-center">
                                        <div class="col-lg-12">
                                            {% if day.day == 1 %}
                                                <b>Lunes</b>
                                            {% elif day.day == 2 %}
                                                <b>Martes</b>
                                            {% elif day.day == 3 %}
                                                <b>Mi&ecaute;rcoles</b>
                                            {% elif day.day == 4 %}
                                                <b>Jueves</b>
                                            {% endif %}
                                        </div>
                                        <div class="col-lg-12">
                                            {% if day.active %}
                                                <div class="text-success"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></div>
                                            {% else %}
                                                <div class="text-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></div>
                                            {% endif %}
                                        </div>
                                        <div class="col-lg-12">
                                            {% if day.departTime != "" %}
                                                Salida: {{ day.departTime }}
                                            {% else %}
                                                <span class="text-warning glyphicon glyphicon-remove" aria-hidden="true"></span>
                                            {% endif %}
                                        </div>
                                        <div class="col-lg-12">
                                            {% if day.returnTime != "" %}
                                                Vuelta: {{ day.returnTime }}
                                            {% else %}
                                                <span class="text-warning glyphicon glyphicon-remove" aria-hidden="true"></span>
                                            {% endif %}
                                        </div>
                                    </div>
                                {% else %}
                                    <div class="col-lg-4 text-center">
                                        <div class="col-lg-12">
                                            {% if day.day == 5 %}
                                                <b>Viernes</b>
                                            {% elif day.day == 6 %}
                                                <b>S&aacute;bado</b>
                                            {% elif day.day == 7 %}
                                                <b>Domingo</b>
                                            {% endif %}
                                        </div>
                                        <div class="col-lg-12">
                                            {% if day.active %}
                                                <div class="text-success"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></div>
                                            {% else %}
                                                <div class="text-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></div>
                                            {% endif %}
                                        </div>
                                        <div class="col-lg-12">
                                            {% if day.departTime != "" %}
                                                Salida: {{ day.departTime }}
                                            {% else %}
                                                <span class="text-warning glyphicon glyphicon-remove" aria-hidden="true"></span>
                                            {% endif %}
                                        </div>
                                        <div class="col-lg-12">
                                            {% if day.returnTime != "" %}
                                                Vuelta: {{ day.returnTime }}
                                            {% else %}
                                                <span class="text-warning glyphicon glyphicon-remove" aria-hidden="true"></span>
                                            {% endif %}
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                      </div>
                        </div>
                    </div>
                    <div class="col-lg-12"><br></div>
                    <div class="col-lg-12 text-center"><a href="/route/show?routeId={{ route.id }}" class="btn btn-primary">Ver m&aacute;s detalles</a> {% if request.user.id != route.user.user_account.id and user.is_authenticated %}<a href="/route/user/apply?routeId={{ route.id }}" class="btn btn-primary">Solicitar</a>{% endif %}</div>
                    <div class="col-lg-12"><br></div>
                    {% if not forloop.last %}
                        <div class="col-lg-12 text-center"><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span><span class="text-primary glyphicon glyphicon-minus" aria-hidden="true"></span></div>
                        <div class="col-lg-12"><br></div>
                    {% endif %}

        {% endfor %}
    <b style="color: transparent">Desarrollado por: Rub&eacute;n G&oacute;mez Barrera</b>
    </div>
{% endblock %}